apiVersion: v1
appVersion: "1.0"
description: Eclipse 是一个开放源代码的、基于Java的可扩展开发平台。就其本身而言，它只是一个框架和一组服务，用于通过插件组件构建开发环境。幸运的是，Eclipse 附带了一个标准的插件集，包括Java开发工具（Java Development Kit，JDK）
icon: https://raw.githubusercontent.com/sanbaideng/rancherapp/master/charts/icons/eclipse-logo.png
keywords:
- gui
name: eclipse
version: 0.1.0
