apiVersion: v1
appVersion: "1.0"
description: GNOME下一款强大的邮件和日程管理程序
icon: https://raw.githubusercontent.com/sanbaideng/rancherapp/master/charts/icons/evolution.png
keywords:
- gui
name: evolution
version: 0.1.0
