apiVersion: v1
appVersion: "1.0"
description: NetBeans是Sun公司（2009年被甲骨文收购）在2000年创立的开放源代码供开发人员和客户社区的家园，旨在构建世界级的Java IDE
icon: https://raw.githubusercontent.com/sanbaideng/rancherapp/master/charts/icons/netbeans.jpg
keywords:
- gui
name: netbeans
version: 0.1.0
